package webui

import (
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"math"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"
)

// The UI must be baked into the binary (go:embed) — non-empty and real HTML.
func TestEmbeddedIndexIsPresent(t *testing.T) {
	if len(indexHTML) == 0 {
		t.Fatal("index.html was not embedded (empty)")
	}
	s := string(indexHTML)
	for _, want := range []string{"<!DOCTYPE html>", "/api/events", "id=\"queue\"", "id=\"history\""} {
		if !strings.Contains(s, want) {
			t.Fatalf("embedded index.html missing %q", want)
		}
	}
}

func TestHandlerServesIndexAtRoot(t *testing.T) {
	h := Handler()
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("GET /: code %d, want 200", rec.Code)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/html") {
		t.Fatalf("Content-Type = %q, want text/html", ct)
	}
	if csp := rec.Header().Get("Content-Security-Policy"); csp == "" {
		t.Fatal("missing Content-Security-Policy header")
	}
	body, _ := io.ReadAll(rec.Body)
	if !strings.Contains(string(body), "<title>holdfast</title>") {
		t.Fatal("served body is not the dashboard page")
	}
}

// The honesty constraint is a REFUSAL, not a preference (TRANSCODE-14). The page may
// state what a VMAF number licenses, but it must NEVER call an encode visually lossless
// or identical, never grade it, and never rank two files' scores. These are properties
// of the page SOURCE — the render is client-side, so the forbidden strings must not
// exist in the template at all, and the honest labels must.
func TestHonestCopy_NoOverclaimStringsPresent(t *testing.T) {
	s := strings.ToLower(string(indexHTML))
	// Verboten: fidelity claims VMAF does not license, and grades that rank a score.
	for _, banned := range []string{
		"visually lossless", "lossless", "identical", "no visible artifacts",
		"no visible artefacts", "indistinguishable", "perfect quality",
		"grade a", "grade b", "5 stars", "★",
	} {
		if strings.Contains(s, banned) {
			t.Errorf("index.html must not claim %q — VMAF licenses no such statement", banned)
		}
	}
}

// The score is meaningless without its viewing condition, so the page shows the model,
// the pooling, the luma-only blind spot, and BOTH pooled statistics — mean AND worst.
func TestHonestCopy_ShowsModelPoolingAndWorstFrame(t *testing.T) {
	s := string(indexHTML)
	for _, want := range []string{
		"vmaf_model",  // the model travels with the score
		"vmaf_min",    // the worst-frame statistic is rendered, not just the mean
		"worst frame", // and labelled as such
		"luma-only",   // the documented blind spot is shown, not buried
		"pooling",     // how the score was pooled
		"vs your source",
		"not recorded", // a nil outcome renders honestly, never as 0
	} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html missing honest-copy element %q", want)
		}
	}
}

// The page must render the persisted outcome facts and the durable lifetime total, and
// key skips off the engine's guard vocabulary rather than the bare word "skipped".
func TestDashboard_RendersOutcomeFields(t *testing.T) {
	s := string(indexHTML)
	for _, want := range []string{
		"bytes_reclaimed_lifetime", // the durable total, not just the session counter
		"source_bytes", "output_bytes", "encode_ms", "encoder",
		"hardlinked", "low-bitrate", "already-at-target-codec", // guard labels
	} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html missing outcome/guard element %q", want)
		}
	}
}

// The pre-rename brand must be gone from the heading (TRANSCODE-14 also fixes this
// cosmetic leak). The banned identifier `trans`+`code` as an adjacent split must not
// appear; the title/heading say holdfast.
func TestBrand_NoPreRenameHeading(t *testing.T) {
	s := string(indexHTML)
	if strings.Contains(s, "trans<span") {
		t.Error("index.html still renders the pre-rename brand in the heading")
	}
	if !strings.Contains(s, "hold<span") && !strings.Contains(s, ">holdfast<") {
		t.Error("index.html heading does not show the holdfast brand")
	}
}

// TRANSCODE-15 (1): the render idiom. Rows are built as DOM nodes (createElement +
// textContent), NEVER by assigning an HTML string to a sink — the untrusted data here is
// attacker-influencable media file paths. The page must therefore contain no HTML-sink
// assignment at all: no innerHTML / outerHTML / insertAdjacentHTML / document.write.
//
// WEBUI-10 extends it across EVERY source module. The page is now generated by
// concatenating them, so a sink in any one of them is a sink in the served document, and
// checking only the generated file would leave the source it came from unchecked.
func TestRenderIdiom_NoHTMLStringSinkFromJobData(t *testing.T) {
	files := map[string]string{"internal/webui/index.html": string(indexHTML)}
	for _, p := range dashboardSources(t) {
		files[p] = readFile(t, p)
	}
	if len(files) < 5 {
		t.Fatalf("the render-idiom sweep is looking at only %d files; it must cover every module", len(files))
	}
	for name, body := range files {
		if probs := htmlSinkProblems(body); probs != nil {
			t.Errorf("%s uses an HTML-string sink (%s) — rows must be built with createElement + "+
				"textContent, so an attacker-influencable path is inert text", name, strings.Join(probs, ", "))
		}
	}
	// The check must BITE: the same sweep over a module that DOES assign job data to a
	// sink has to report it, for every sink the criterion names.
	for _, bad := range []string{
		`el.innerHTML = j.path;`,
		`el.outerHTML = "<td>" + j.path + "</td>";`,
		`el.insertAdjacentHTML("beforeend", j.reason);`,
		`document.write(a.covers);`,
		`el.srcdoc = j.path;`,
		`document.createRange().createContextualFragment(j.path);`,
		`new DOMParser().parseFromString(j.path, "text/html");`,
		`el.setHTMLUnsafe(j.path);`,
		`eval("render(" + j.path + ")");`,
		`new Function("return " + j.path)();`,
	} {
		if htmlSinkProblems(bad) == nil {
			t.Errorf("the render-idiom sweep passed %q, so it cannot fail", bad)
		}
	}
	// And the prescribed structure primitives are actually used.
	s := string(indexHTML)
	for _, want := range []string{"createElement", "textContent", "<template", ".content.cloneNode"} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html missing the safe-render primitive %q", want)
		}
	}
}

// htmlSinkProblems names every way a body reaches the DOM through a string rather than
// through a node. `document.write` and the parse-a-string constructors are equivalents of
// innerHTML for this purpose: each turns text into markup.
func htmlSinkProblems(body string) []string {
	var out []string
	for _, sink := range []string{
		"innerHTML", "outerHTML", "insertAdjacentHTML", "document.write",
		"srcdoc", "createContextualFragment", "DOMParser", "setHTMLUnsafe",
		"eval(", "new Function(",
	} {
		if strings.Contains(body, sink) {
			out = append(out, sink)
		}
	}
	return out
}

// dashboardSources is every file the generated document is built from, plus the unit
// suite that exercises them.
func dashboardSources(t *testing.T) []string {
	t.Helper()
	var out []string
	err := filepath.WalkDir(srcDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			out = append(out, p)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v", srcDir, err)
	}
	return out
}

// B16. The response Content-Security-Policy still contains `default-src 'none'` and
// `require-trusted-types-for 'script'`, and adds NO source expression admitting a resource
// or an evaluation the current policy refuses.
//
// The byte-for-byte assertion below (TestCSP_ByteForByteUnchangedAndStillEnforcesTrustedTypes)
// catches any change at all. This one says WHICH changes are the dangerous ones, and is
// proved against a table of policies that each widen it by exactly one thing - so it is a
// rule about policies, not a second copy of the string.
func TestCSP_AdmitsNothingTheCurrentPolicyRefuses(t *testing.T) {
	rec := httptest.NewRecorder()
	Handler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))
	got := rec.Header().Get("Content-Security-Policy")
	if probs := cspProblems(got); probs != nil {
		t.Errorf("the served policy %q admits something it must not: %v", got, probs)
	}

	// The rule must BITE. Each of these is a real way this policy gets widened.
	for _, widened := range []string{
		"default-src 'self'; require-trusted-types-for 'script'",
		"default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval'; require-trusted-types-for 'script'",
		"default-src 'none'; img-src 'self'; require-trusted-types-for 'script'",
		"default-src 'none'; img-src data:; require-trusted-types-for 'script'",
		"default-src 'none'; script-src 'unsafe-inline' https://cdn.example.com; require-trusted-types-for 'script'",
		"default-src 'none'; script-src 'nonce-abc123'; require-trusted-types-for 'script'",
		"default-src 'none'; script-src 'sha256-abc'; require-trusted-types-for 'script'",
		"default-src 'none'; script-src 'strict-dynamic'; require-trusted-types-for 'script'",
		"default-src 'none'; connect-src *; require-trusted-types-for 'script'",
		"default-src 'none'; require-trusted-types-for 'script'; trusted-types default",
		"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'",
		"style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; require-trusted-types-for 'script'",
	} {
		if cspProblems(widened) == nil {
			t.Errorf("the policy rule accepted a widened policy, so it cannot fail: %q", widened)
		}
	}
}

// cspProblems reports every way a policy is weaker than the one this page is served with.
//
// The allow-list is a CLOSED set on purpose. A directive nobody thought about, or a source
// expression that names a host, a scheme, a nonce or a hash, is exactly the change that
// passes a "still contains default-src 'none'" test and quietly opens the page up.
func cspProblems(policy string) []string {
	allowedDirectives := map[string][]string{
		"default-src":               {"'none'"},
		"style-src":                 {"'unsafe-inline'"},
		"script-src":                {"'unsafe-inline'"},
		"connect-src":               {"'self'"},
		"require-trusted-types-for": {"'script'"},
	}
	var out []string
	seen := map[string]bool{}
	for _, raw := range strings.Split(policy, ";") {
		fields := strings.Fields(raw)
		if len(fields) == 0 {
			continue
		}
		name := strings.ToLower(fields[0])
		seen[name] = true
		allowed, ok := allowedDirectives[name]
		if !ok {
			out = append(out, "the directive "+name+" is not in the policy this page is served with")
			continue
		}
		for _, src := range fields[1:] {
			if !slices.Contains(allowed, strings.ToLower(src)) {
				out = append(out, "the directive "+name+" carries the source expression "+src+
					", which admits something the current policy refuses")
			}
		}
	}
	for name := range allowedDirectives {
		if !seen[name] {
			out = append(out, "the directive "+name+" is missing")
		}
	}
	return out
}

// TRANSCODE-15 (1): Trusted Types is adopted — the response CSP enforces it, turning the
// no-string-sink discipline into a browser-enforced guarantee.
func TestTrustedTypes_EnforcedByCSP(t *testing.T) {
	rec := httptest.NewRecorder()
	Handler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))
	csp := rec.Header().Get("Content-Security-Policy")
	if !strings.Contains(csp, "require-trusted-types-for 'script'") {
		t.Fatalf("CSP does not enforce Trusted Types: %q", csp)
	}
}

// contrastRatio is the WCAG 2.x relative-luminance contrast ratio between two #rrggbb
// colors — the measurement the a11y test asserts against, not an eyeballed guess.
func contrastRatio(t *testing.T, hexA, hexB string) float64 {
	t.Helper()
	lum := func(hex string) float64 {
		var rgb [3]float64
		for i := 0; i < 3; i++ {
			var v int
			for _, c := range hex[1+i*2 : 3+i*2] {
				v *= 16
				switch {
				case c >= '0' && c <= '9':
					v += int(c - '0')
				case c >= 'a' && c <= 'f':
					v += int(c-'a') + 10
				case c >= 'A' && c <= 'F':
					v += int(c-'A') + 10
				default:
					t.Fatalf("bad hex color %q", hex)
				}
			}
			c := float64(v) / 255
			if c <= 0.03928 {
				rgb[i] = c / 12.92
			} else {
				rgb[i] = math.Pow((c+0.055)/1.055, 2.4)
			}
		}
		return 0.2126*rgb[0] + 0.7152*rgb[1] + 0.0722*rgb[2]
	}
	la, lb := lum(hexA), lum(hexB)
	hi, lo := math.Max(la, lb), math.Min(la, lb)
	return (hi + 0.05) / (lo + 0.05)
}

// cssVar extracts a `--name:#rrggbb` token value from the embedded page.
func cssVar(t *testing.T, name string) string {
	t.Helper()
	m := regexp.MustCompile(name + `:\s*(#[0-9a-fA-F]{6})`).FindStringSubmatch(string(indexHTML))
	if m == nil {
		t.Fatalf("CSS token %s not found", name)
	}
	return m[1]
}

// TRANSCODE-15 (2): a11y, MEASURED. The border token that draws every button/input edge
// must clear WCAG 2.2's 3:1 non-text floor on the page background (the shipped default
// --line was 1.31:1), and body text must clear the 4.5:1 text floor.
func TestAccessibility_ContrastMeasured(t *testing.T) {
	bg := cssVar(t, "--bg")
	if got := contrastRatio(t, cssVar(t, "--border"), bg); got < 3.0 {
		t.Errorf("--border on --bg is %.2f:1, under the 3:1 non-text floor", got)
	}
	if got := contrastRatio(t, cssVar(t, "--fg"), bg); got < 4.5 {
		t.Errorf("--fg on --bg is %.2f:1, under the 4.5:1 text floor", got)
	}
	// The border token must actually be the one drawing the interactive edges, not a
	// defined-but-unused value: buttons and control inputs reference it.
	s := string(indexHTML)
	if !strings.Contains(s, "button {") || !strings.Contains(s, "border: var(--bw-hair) solid var(--border)") {
		t.Error("buttons/inputs do not draw their border from the accessible --border token")
	}
}

// TRANSCODE-15 (2): a keyboard user must see focus and the token field must have a real
// label (not just a placeholder); the SSE regions get a POLITE summary region, not a
// live-region on the whole table (which would spam a screen reader on every snapshot).
func TestAccessibility_FocusLabelAndPoliteLiveRegion(t *testing.T) {
	s := string(indexHTML)
	if !strings.Contains(s, ":focus-visible") {
		t.Error("no :focus-visible ring — a keyboard-only pass has no visible focus")
	}
	if !strings.Contains(s, `<label for="token"`) {
		t.Error("the token field has no <label> (a placeholder is not a label)")
	}
	if !strings.Contains(s, `aria-live="polite"`) {
		t.Error("no polite aria-live region for the SSE-driven updates")
	}
	// The polite summary must be a small status region, NOT aria-live on the job table.
	if regexp.MustCompile(`<t(able|body)[^>]*aria-live`).MatchString(s) {
		t.Error("aria-live is on the table itself — that spams a screen reader on every snapshot; announce a summary region instead")
	}
}

// TRANSCODE-15 (3): the silent row caps are surfaced and Pause is disabled once paused.
func TestInteraction_CapsSurfacedAndPauseDisabled(t *testing.T) {
	s := string(indexHTML)
	if !strings.Contains(s, "this view is capped") {
		t.Error("the API row caps are not surfaced — a truncated view reads as complete")
	}
	if !strings.Contains(s, `$("pause").disabled = !!snap.paused`) {
		t.Error("Pause is not disabled when already paused")
	}
	if !strings.Contains(s, `id="filter"`) {
		t.Error("no filter control for the queue/history views")
	}
}

// --- in-flight legibility (S0030) --------------------------------------------

// TestQueue_RendersInStateElapsedDerivedFromTheWireTimestamp is AC1. The elapsed figure
// must be DERIVED from the transition timestamp on every tick, never accumulated in a
// counter here: a background tab's timers are throttled by policies with no normative
// guarantee, so a counter would drift while a recomputed value cannot. The proof is
// structural, because the render is client-side: the page must read updated_at into the
// row, take the server's own clock off the snapshot, recompute on a timer, and hold no
// running total of its own.
func TestQueue_RendersInStateElapsedDerivedFromTheWireTimestamp(t *testing.T) {
	s := string(indexHTML)
	for _, want := range []string{
		"j.updated_at", // the transition timestamp already on the wire is the basis
		"snap.now",     // ...read against the SERVER's clock, not the client's alone
		"clockOffset",  // ...so a skewed client clock cannot invent an age
		"refreshElapsed",
		"setInterval(refreshElapsed, 1000)", // refreshed with no page reload
		"dataset.since",                     // each row carries its own basis
		"<th>Elapsed</th>",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html missing the elapsed-from-timestamp element %q", want)
		}
	}
	// An accumulating counter is the specific thing AC1 forbids. `now - since` is the
	// only arithmetic that may produce the figure.
	if !strings.Contains(s, "now - since") {
		t.Error("the elapsed figure is not computed as (server now - transition timestamp)")
	}
	for _, banned := range []string{"elapsed++", "elapsed += ", "seconds++", "+= 1000"} {
		if strings.Contains(s, banned) {
			t.Errorf("index.html accumulates elapsed time (%q) instead of deriving it — a throttled tab would drift", banned)
		}
	}
}

// TestQueue_RendersProgressAndShowsAbsenceAsAbsence is AC3's page half: a running encode
// shows a figure taken from the encoder's own stream, and a row with no measurement reads
// the page's ONE absence phrase - never a stale figure, never an interpolated one, never
// a zero.
//
// S0053 changed two things here and both are asserted, not dropped. The absent-figure
// word was "unknown" and is now that one phrase, because F3 requires the SAME phrase in
// every field that can carry an absence. And the paragraphs explaining what the figure is
// measured against moved off the surface into the linked document (F8) - so the claims
// are asserted where they now live rather than deleted from the assertion.
func TestQueue_RendersProgressAndShowsAbsenceAsAbsence(t *testing.T) {
	s := string(indexHTML)
	for _, want := range []string{
		"progress_fraction", "progress_seconds", "progress_duration_seconds",
		"<th>Progress</th>",
		"td.appendChild(nrNode());", // the honest absent-figure node
	} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html missing progress element %q", want)
		}
	}
	doc := readRepoDoc(t, DocPath)
	for _, want := range []string{
		"never a stale figure",
		"encoder's own progress stream",
	} {
		if !strings.Contains(doc, want) {
			t.Errorf("%s missing the progress claim %q, which moved off the surface under F8", DocPath, want)
		}
	}
	// The empty-queue rendering is one entry in the per-view state vocabulary rather than
	// a literal at the call site, and the column span comes from the same table. The
	// WORDING is S0052's to set - it may not repeat the heading above the row or a column
	// header beneath it - so what is pinned here is that the entry exists and says, in
	// words, that the view has nothing to show.
	if !strings.Contains(s, `empty: "No work in hand."`) {
		t.Error("the empty-queue rendering was changed")
	}
	if !strings.Contains(s, `const VIEW_COLUMNS = { queue: 5, history: 7 };`) {
		t.Error("the empty-queue row does not span the queue table's columns")
	}
}

// TestQueue_ProgressIsShownForARunningEncodeOnly is the page half of the rule the hub
// enforces on the wire. A progress figure is a measurement taken BY the encoder against
// the source duration, so it exists while the encoder runs and at no other time, and the
// spec puts the rest of the pipeline outside it in terms:
//
//	Out (explicit):
//	- A progress percentage for the verify/VMAF phase. `internal/vmaf` keeps its
//	  current invocation; the verifying state is covered by elapsed alone (AC1).
//
// Gating the cell on the whole active set is what put the finished encode's last
// percentage on a verifying row and left it frozen there for the whole verify phase —
// which on a feature-length source is the longest stretch an operator watches.
func TestQueue_ProgressIsShownForARunningEncodeOnly(t *testing.T) {
	s := string(indexHTML)
	if !strings.Contains(s, `const PROGRESS_STATUS = "encoding";`) {
		t.Error("the page does not name the one state a progress figure can exist in")
	}
	if !strings.Contains(s, `if (j.status !== PROGRESS_STATUS) return null;`) {
		t.Error("the progress derivation is not restricted to a running encode")
	}
	if strings.Contains(s, "ACTIVE_STATUSES") {
		t.Error("the progress cell is gated on the whole active set again — a verifying row would carry the finished encode's figure")
	}
	// And the copy says so, because the operator reading an empty Progress cell on a
	// verifying row is owed the reason.
	if !strings.Contains(s, "covered by\n      Elapsed alone") && !strings.Contains(s, "covered by Elapsed alone") {
		t.Error("the queue note does not say that a probed/verified file is covered by Elapsed alone")
	}
}

// TestQueue_ProgressAddsNoHTMLSinkAndNoExternalAsset is AC11. The new cells are built
// with the same DOM-node idiom as every other row (TestRenderIdiom already forbids the
// string sinks page-wide), the CSP is unchanged, and the page still fetches nothing from
// outside the binary that served it.
func TestQueue_ProgressAddsNoHTMLSinkAndNoExternalAsset(t *testing.T) {
	s := string(indexHTML)
	// No off-binary fetch: no absolute URL, no protocol-relative one, and the only
	// network call is to this server's own API.
	for _, banned := range []string{"http://", "https://", "//cdn", "src=\"//", "@import", "url(http"} {
		if strings.Contains(s, banned) {
			t.Errorf("index.html would fetch %q from outside the binary that served it", banned)
		}
	}
	// The CSP is exactly the one that was already enforced, Trusted Types included.
	rec := httptest.NewRecorder()
	Handler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))
	const want = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; require-trusted-types-for 'script'"
	if got := rec.Header().Get("Content-Security-Policy"); got != want {
		t.Errorf("the response CSP changed.\n got: %q\nwant: %q", got, want)
	}
	// The progress cell is assembled from nodes and text, like every other cell.
	if !strings.Contains(s, "function progressCell(td, j)") {
		t.Fatal("no progressCell renderer")
	}
	// The elapsed cell is filled from the derivation and from nothing else: a text node
	// when there is an age, and the page's absence node when there is not (F3).
	if !strings.Contains(s, `if (age === null) td.replaceChildren(nrNode());`) ||
		!strings.Contains(s, `else td.textContent = age;`) {
		t.Error("the elapsed cell is not filled with textContent")
	}
}

// --- DASH-7: the whole-ledger aggregates on the page -------------------------

// The page renders each published aggregate with the set it covers and the rows that
// were excluded for want of a recorded value. Rendering is client-side, so these are
// properties of the page SOURCE: the keys it reads, the statements it draws.
func TestDashboard_RendersTheWholeLedgerAggregatesWithTheirCoverage(t *testing.T) {
	s := string(indexHTML)
	for _, want := range []string{
		// every published figure is read by name
		`"outcomes"`, `"skips_by_guard"`, `"size_ratio"`, `"encode_ms"`, `"vmaf_mean"`, `"vmaf_min"`,
		// and each is drawn with its coverage, its window when bounded, and its exclusions
		`"over " + ((a && a.covers)`, "a.window", "excluded: no recorded value",
		"Across the whole ledger",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html does not render the aggregates properly: missing %q", want)
		}
	}
	// The figures must come from the snapshot's aggregates, not be recomputed in the
	// browser from the capped rows the tables were handed.
	if !strings.Contains(s, "renderAggregates(snap.aggregates)") {
		t.Error("the page does not render the server-computed aggregates from the snapshot")
	}
}

// An aggregate that could not be read is drawn AS unavailable, and the rest of the page
// still draws. Three independent guarantees, each asserted: the card checks its own
// `available` flag, each card is built inside its own try/catch so one throwing figure
// cannot take the others, and the whole aggregate render happens AFTER the queue and
// history rows are already on the page.
func TestDashboard_AnUnavailableAggregateStillLeavesThePageRendering(t *testing.T) {
	s := string(indexHTML)
	if !strings.Contains(s, "a.available !== true") {
		t.Error("a card does not check whether its figure is available, so an unreadable figure would render as data")
	}
	if !strings.Contains(s, `v.appendChild(mk("span", "nr", "unavailable"))`) {
		t.Error("an unavailable figure is not drawn as unavailable")
	}
	if !strings.Contains(s, "card = aggCard(null, title, nodes);") {
		t.Error("cards are not built independently - one figure that throws would take the others with it")
	}
	// The tables are RECONCILED rather than rebuilt (a row the snapshot did not change
	// keeps its own node), so the call this looks for is the reconciliation and not an
	// append. What is being decided is unchanged and is a property of the CODE's order,
	// which is why it is read from the source here and not from a render.
	hist := strings.Index(s, "syncRows(hbody,")
	agg := strings.Index(s, "renderAggregates(snap.aggregates)")
	if hist < 0 || agg < 0 || agg < hist {
		t.Errorf("the aggregates render before the tables (history at %d, aggregates at %d) - an aggregate failure could then cost the rows", hist, agg)
	}
	if !strings.Contains(s, `try { renderAggregates(snap.aggregates); } catch (_) { setViewState("aggs", "unreadable"); }`) {
		t.Error("the aggregate render is not guarded, so a throw inside it would abort the rest of render()")
	}
	// A figure with nothing recorded reads as "not recorded", never as 0.
	if !strings.Contains(s, "if (counted === 0) {") || !strings.Contains(s, "v.appendChild(nrNode());") {
		t.Error("an aggregate with no contributing row is not rendered as 'not recorded'")
	}
}

// The response the page is served with is unchanged by this phase: the same
// Content-Security-Policy, byte for byte, and Trusted Types still required. Asserted
// against the literal policy rather than a substring, because a widened CSP is exactly
// the kind of change that passes a "contains" check.
func TestCSP_ByteForByteUnchangedAndStillEnforcesTrustedTypes(t *testing.T) {
	const want = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; " +
		"connect-src 'self'; require-trusted-types-for 'script'"
	rec := httptest.NewRecorder()
	Handler().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))
	if got := rec.Header().Get("Content-Security-Policy"); got != want {
		t.Errorf("Content-Security-Policy changed\n got: %q\nwant: %q", got, want)
	}
}

// The page fetches nothing from outside the binary that served it. `default-src 'none'`
// would block it anyway, but a page that TRIES is a page that renders broken behind the
// policy, so the source itself must name no off-binary origin.
func TestPage_FetchesNothingFromOutsideTheBinaryThatServedIt(t *testing.T) {
	s := string(indexHTML)
	for _, banned := range []string{"http://", "https://", "//cdn", "@import", "<script src", "<link rel"} {
		if strings.Contains(s, banned) {
			t.Errorf("index.html reaches outside the binary: %q", banned)
		}
	}
	// The only origin the page talks to is its own server.
	for _, want := range []string{`new EventSource("/api/events")`} {
		if !strings.Contains(s, want) {
			t.Errorf("index.html no longer talks to its own API: missing %q", want)
		}
	}
}

// --- DASH-9: the drawings cost the dashboard no dependency ----------------------

// The figures this phase adds are DOM nodes built from values the server already
// published, cloned out of templates in the page's own markup. That is not a style
// preference: the response Content-Security-Policy this page is served with is
// `default-src 'none'`, and `img-src`, `font-src` and `media-src` all fall back to it, so
// a charting library, a webfont, an image and a `data:` image are each already forbidden
// by the response the binary sends. A dependency added here would therefore not be a
// heavier page, it would be a BROKEN one - and the only way to make it work would be to
// widen the very policy this phase's fail-safe forbids widening.
//
// So the absence is asserted, over the whole of internal/webui: no package manifest, no
// lockfile, no vendored library, no font file, no image file, and a generator whose
// imports are still standard library only.
func TestNoNewDependency_TheDashboardShipsNothingButItsOwnSource(t *testing.T) {
	bannedName := map[string]string{
		"package.json": "a package manifest", "package-lock.json": "a lockfile",
		"npm-shrinkwrap.json": "a lockfile", "yarn.lock": "a lockfile",
		"pnpm-lock.yaml": "a lockfile", "bun.lockb": "a lockfile",
		"deno.json": "a package manifest", "bower.json": "a package manifest",
		".npmrc": "a registry configuration", "requirements.txt": "a package manifest",
	}
	bannedDir := map[string]string{
		"node_modules": "an installed dependency tree", "vendor": "a vendored library tree",
		"dist": "a bundler output tree", "fonts": "a font tree",
	}
	bannedExt := map[string]string{
		".woff": "a font file", ".woff2": "a font file", ".ttf": "a font file",
		".otf": "a font file", ".eot": "a font file",
		".png": "an image file", ".jpg": "an image file", ".jpeg": "an image file",
		".gif": "an image file", ".webp": "an image file", ".avif": "an image file",
		".ico": "an image file", ".bmp": "an image file", ".svg": "an image file",
		".map": "a bundler source map", ".lock": "a lockfile",
	}
	// The whole of what internal/webui is allowed to be made of.
	allowedExt := map[string]bool{
		".go": true, ".js": true, ".css": true, ".html": true, ".tmpl": true, ".txt": true,
	}
	// The graders' own project (internal/webui/e2e) is TEST tooling and is made of a few
	// more things: an ES-module spec, a snapshot fixture, a manifest and its lockfile. It
	// is exempted HERE and nowhere else, and the exemption is narrow on purpose - a font,
	// an image, a minified bundle, a vendored tree or a bundler output is still refused
	// there, because none of those is anything a grader needs.
	//
	// What the exemption cannot do is let a dependency reach a reader: nothing under e2e
	// is embedded, served or built into the binary, and that is not asked for on trust -
	// TestBuild_TheTestOnlyDependencyCannotReachTheBuiltArtifact proves the generator, the
	// generated document, the Dockerfile and go.mod are each free of it.
	e2eExt := map[string]bool{".mjs": true, ".json": true, ".md": true}
	// A dotfile's whole name IS its extension as far as filepath.Ext is concerned, so the
	// graders' project names the few it carries: its manifest, its lockfile, the paths it
	// keeps out of the repository, and the registry configuration that DISABLES lifecycle
	// scripts for it (scripts/check-pins.sh requires that decision to exist and be
	// committed, so this must admit the file that records it).
	e2eName := map[string]bool{
		"package.json": true, "package-lock.json": true, ".gitignore": true, ".npmrc": true,
	}
	inE2E := func(p string) bool {
		s := filepath.ToSlash(p)
		return s == "e2e" || strings.HasPrefix(s, "e2e/")
	}
	// What the graders' project keeps OUT of the repository, read from its own .gitignore
	// rather than restated here. Those paths are the runner's output - an installed tree, a
	// failed case's screenshots and trace, the JSON report - and none of them is repository
	// content this sweep has to account for. Reading the ignore file is what keeps the two
	// in step: a second list would agree with the first today and diverge the first time
	// the runner learns a new output directory, whereupon `make check` would red over a
	// file nobody committed, having been green over the run that produced it.
	e2eIgnored := readE2EIgnores(t)

	var goFiles []string
	seen := 0
	err := filepath.WalkDir(".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name := d.Name()
		if d.IsDir() {
			// An installed tree or a run's output under the graders' project is skipped
			// whole: nothing inside somebody else's package, and nothing the runner wrote
			// and git never took, is this repository's to account for.
			if inE2E(p) && e2eIgnored[name] {
				return filepath.SkipDir
			}
			if what, bad := bannedDir[name]; bad && p != "." {
				return fmt.Errorf("%s is %s: the dashboard is served under default-src 'none' and can fetch none of it", p, what)
			}
			return nil
		}
		if inE2E(p) && e2eIgnored[name] {
			return nil
		}
		seen++
		ext := strings.ToLower(filepath.Ext(name))
		if inE2E(p) {
			// The graders' project. The bans that protect a READER still apply; the ones
			// that only said "this repository declares no dependency" do not.
			if what, bad := bannedExt[ext]; bad {
				t.Errorf("%s is %s; a grader needs none of those, and internal/webui ships none", p, what)
			}
			if strings.HasSuffix(name, ".min.js") {
				t.Errorf("%s is a minified bundle; every script this repository wrote is source", p)
			}
			if !e2eExt[ext] && !allowedExt[ext] && !e2eName[name] {
				t.Errorf("%s has the extension %q, which is not one the graders' project is made of (%v plus %v)",
					p, ext, sortedKeys(allowedExt), sortedKeys(e2eExt))
			}
			return nil
		}
		if what, bad := bannedName[name]; bad {
			t.Errorf("%s is %s; this dashboard has no third-party dependency to declare", p, what)
		}
		if what, bad := bannedExt[ext]; bad {
			t.Errorf("%s is %s; the page's own policy forbids fetching one and its figures are drawn as DOM nodes instead", p, what)
		}
		if !allowedExt[ext] {
			t.Errorf("%s has the extension %q, which is not one internal/webui is made of (%v)", p, ext, sortedKeys(allowedExt))
		}
		if strings.HasSuffix(name, ".min.js") {
			t.Errorf("%s is a minified bundle; every script here is source this repository wrote", p)
		}
		if ext == ".go" && strings.HasPrefix(filepath.ToSlash(p), "gen/") {
			goFiles = append(goFiles, p)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking internal/webui: %v", err)
	}
	if seen < 10 {
		t.Fatalf("the sweep looked at only %d files; it must cover the whole of internal/webui", seen)
	}
	if len(goFiles) == 0 {
		t.Fatal("the sweep found no generator source to check the imports of")
	}

	// The generator's imports: the standard library, plus this repository's own packages.
	// `make build` is a plain `go build` and the image gains no stage and no tool, which
	// is only true while this holds. The module path is read from go.mod rather than
	// spelled here, so a rename cannot silently turn this repo's own code into a
	// third-party dependency in the eyes of this assertion (TRANSCODE-12 renamed it once).
	self := moduleName(t)
	fset := token.NewFileSet()
	checked := 0
	for _, p := range goFiles {
		f, err := parser.ParseFile(fset, p, nil, parser.ImportsOnly)
		if err != nil {
			t.Fatalf("parsing %s: %v", p, err)
		}
		for _, im := range f.Imports {
			path, err := strconv.Unquote(im.Path.Value)
			if err != nil {
				t.Fatalf("%s: unquoting import %s: %v", p, im.Path.Value, err)
			}
			checked++
			if !ownImport(path, self) {
				t.Errorf("%s imports %q, which is neither the standard library nor this repository: the generator runs with the Go toolchain alone", p, path)
			}
		}
	}
	if checked == 0 {
		t.Fatal("no import was checked at all, so this assertion cannot fail")
	}
	// The rule must BITE: anything outside the standard library and this module is
	// reported, including a charting library, which is the specific thing a page of
	// figures invites and this page's own policy could never load.
	for _, foreign := range []string{
		"golang.org/x/net/html",
		"gopkg.in/yaml.v3",
		"example.com/charts",
		"github.com/wcharczuk/go-chart/v2",
		"github.com/NSchatzOther/holdfast/internal/webui",
	} {
		if ownImport(foreign, self) {
			t.Errorf("the dependency rule accepted %q, so it cannot fail", foreign)
		}
	}
	for _, ours := range []string{"bytes", "io/fs", "path/filepath", "os", self + "/internal/webui/gen"} {
		if !ownImport(ours, self) {
			t.Errorf("the dependency rule rejected %q, which is the standard library or this repository", ours)
		}
	}
}

// readE2EIgnores is the graders' project's own .gitignore, as a set of names. Every entry
// there is a bare name or a name with a trailing slash, which is all this needs to
// understand; a pattern it cannot read is reported rather than silently widening the
// exemption, because an exemption nobody can see is how a sweep stops sweeping.
func readE2EIgnores(t *testing.T) map[string]bool {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("e2e", ".gitignore"))
	if err != nil {
		t.Fatalf("reading the graders' project's .gitignore: %v", err)
	}
	out := map[string]bool{}
	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name := strings.TrimSuffix(line, "/")
		if strings.ContainsAny(name, "/*?[!") {
			t.Errorf("e2e/.gitignore carries the pattern %q, which this sweep reads as a bare name; "+
				"keep the ignore file to plain names so the two cannot disagree about what is untracked output", line)
			continue
		}
		out[name] = true
	}
	if !out["node_modules"] {
		t.Fatal("e2e/.gitignore no longer ignores node_modules; the sweep would then account for somebody else's package tree")
	}
	return out
}

// ownImport applies the Go convention: an import path whose first element carries a dot
// names a host, and a host is a dependency unless it is this module itself.
func ownImport(path, self string) bool {
	first, _, _ := strings.Cut(path, "/")
	if !strings.Contains(first, ".") {
		return true
	}
	return path == self || strings.HasPrefix(path, self+"/")
}

// moduleName reads the module path out of the repository's own go.mod, with no dependency
// on a module-file parser.
func moduleName(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", "go.mod"))
	if err != nil {
		t.Fatalf("reading go.mod: %v", err)
	}
	for _, line := range strings.Split(string(b), "\n") {
		if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.TrimSpace(rest)
		}
	}
	t.Fatal("go.mod names no module")
	return ""
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

func TestHandler404sOtherPaths(t *testing.T) {
	h := Handler()
	req := httptest.NewRequest(http.MethodGet, "/nope.js", nil)
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusNotFound {
		t.Fatalf("GET /nope.js: code %d, want 404", rec.Code)
	}
}
