package commentdensity

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The four comment shapes, with the counts written out. The trailing-comment line is
// the divergence that matters: Go's idiom would otherwise score ordinary code as prose.
const fourShapes = `// Package p is the package doc.
// It spans two lines.
package p

// Answer returns the answer.
func Answer() int {
	return 42 // the answer itself
}

/*
Block comment,
three lines of it.
*/
var x = 1

func blank() {

	_ = x
}
`

// Comment-looking bytes that are not comments: inside an interpreted string, inside a
// raw string, and a whole raw-string line that opens with the comment marker. A counter
// that matched patterns instead of tokens scores this file as prose, which is the exact
// failure that scored mostly-code files at 85% elsewhere.
const noComments = `package p

const site = "https://example.com//not-a-comment"

const doc = @
// looks like a comment
/* and so does this */
@

func use() string {
	return site + doc + "/* nor is this */"
}
`

func TestCommentDensityCountsTheFourCommentShapesExactly(t *testing.T) {
	m, err := Measure("four.go", []byte(fourShapes))
	if err != nil {
		t.Fatalf("Measure: %v", err)
	}
	if m.Prose != 7 || m.Code != 8 {
		t.Errorf("prose=%d code=%d, want prose=7 code=8 (package doc 2, doc comment 1, block 4; "+
			"the trailing-comment line is code)", m.Prose, m.Code)
	}
	if m.Generated {
		t.Error("a file with no generated marker was reported generated")
	}
}

func TestCommentDensityCountsNoProseInCommentLookingBytes(t *testing.T) {
	src := strings.ReplaceAll(noComments, "@", "`")
	m, err := Measure("strings.go", []byte(src))
	if err != nil {
		t.Fatalf("Measure: %v", err)
	}
	if m.Prose != 0 {
		t.Errorf("prose=%d, want 0 - no line of this file is spanned by a comment", m.Prose)
	}
	if m.Code != 9 {
		t.Errorf("code=%d, want 9 - every non-blank line here is code, including the raw string's", m.Code)
	}
}

func TestCommentDensityExcludesTestdataGeneratedAndSmallFiles(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "ok.go", densityFixture(4, 36))
	write(t, dir, filepath.Join("testdata", "loud.go"), densityFixture(35, 6))
	write(t, dir, "generated.go", "// Code generated by hand. DO NOT EDIT.\n"+densityFixture(35, 6))
	write(t, dir, "small.go", densityFixture(20, 5))

	var out bytes.Buffer
	if err := Run(dir, &out, nil); err != nil {
		t.Fatalf("an excluded file was allowed to fail the run: %v\n%s", err, out.String())
	}
	got := out.String()
	if !strings.Contains(got, "1 eligible file(s)") {
		t.Errorf("want exactly one eligible file in the summary:\n%s", got)
	}
	for _, name := range []string{"loud.go", "generated.go", "small.go"} {
		if strings.Contains(got, name) {
			t.Errorf("%s was named by a run that must not measure it:\n%s", name, got)
		}
	}
	if !strings.Contains(got, "ok.go") {
		t.Errorf("the one eligible file was not measured:\n%s", got)
	}
}

func TestCommentDensityFailsAndNamesAFileOverTheCeiling(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "ok.go", densityFixture(4, 36))
	write(t, dir, "loud.go", densityFixture(35, 6))

	var out bytes.Buffer
	err := Run(dir, &out, nil)
	if err == nil {
		t.Fatalf("a file over the %d%% ceiling did not fail the run:\n%s", CeilingPct, out.String())
	}
	if !strings.Contains(err.Error(), "loud.go") {
		t.Errorf("the failure does not name the file: %v", err)
	}
	if !strings.Contains(err.Error(), fmt.Sprintf("%d%% ceiling", CeilingPct)) {
		t.Errorf("the failure does not name the ceiling it broke: %v", err)
	}
	if !strings.Contains(out.String(), "85.4%") {
		t.Errorf("the failure does not report the ratio:\n%s", out.String())
	}
}

func TestCommentDensityWarnsInTheBandAndStaysGreen(t *testing.T) {
	dir := t.TempDir()
	prose := (WarnPct + CeilingPct) * 40 / 200
	body := densityFixture(prose, 40-prose)
	m, err := Measure("banded.go", []byte(body))
	if err != nil {
		t.Fatalf("Measure: %v", err)
	}
	if !m.InBand() {
		t.Fatalf("the fixture is not inside the band: prose=%d code=%d", m.Prose, m.Code)
	}
	write(t, dir, "banded.go", body)
	write(t, dir, "ok.go", densityFixture(4, 36))

	var out bytes.Buffer
	if err := Run(dir, &out, nil); err != nil {
		t.Fatalf("a banded file made the run non-zero: %v", err)
	}
	want := fmt.Sprintf("warn: banded.go at %.1f%%", m.Ratio()*100)
	if !strings.Contains(out.String(), want) {
		t.Errorf("no warning naming the file and its ratio (%q):\n%s", want, out.String())
	}
}

func TestCommentDensityFailsOnAnUnparseableFile(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "ok.go", densityFixture(4, 36))
	write(t, dir, "broken.go", "package p\n\nfunc (\n")

	var out bytes.Buffer
	err := Run(dir, &out, nil)
	if err == nil {
		t.Fatal("an unparseable file was scored rather than reported")
	}
	if !strings.Contains(err.Error(), "broken.go") || !strings.Contains(err.Error(), "cannot be parsed") {
		t.Errorf("the failure does not name the file and the parser's error: %v", err)
	}
	if !strings.Contains(out.String(), "1 eligible file(s)") {
		t.Errorf("the unparseable file was counted in the aggregate:\n%s", out.String())
	}
}

func TestCommentDensityFailsOnAnUnreadableFile(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "ok.go", densityFixture(4, 36))
	secret := filepath.Join(dir, "secret.go")
	write(t, dir, "secret.go", densityFixture(4, 36))
	if err := os.Chmod(secret, 0o000); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(secret, 0o644) })
	if _, err := os.ReadFile(secret); err == nil {
		t.Skip("this user reads a mode-000 file, so the unreadable case cannot be planted here")
	}

	var out bytes.Buffer
	err := Run(dir, &out, nil)
	if err == nil {
		t.Fatal("an unreadable file was treated as absent")
	}
	if !strings.Contains(err.Error(), "secret.go") || !strings.Contains(err.Error(), "cannot be read") {
		t.Errorf("the failure does not name the path and the underlying error: %v", err)
	}
}

func TestCommentDensityFailsOnAnEmptyWalk(t *testing.T) {
	var out bytes.Buffer
	err := Run(t.TempDir(), &out, nil)
	if err == nil {
		t.Fatal("a walk that measured nothing reported a clean tree")
	}
	if !strings.Contains(err.Error(), "no eligible Go file") {
		t.Errorf("the failure does not say the scan measured nothing: %v", err)
	}
}

func TestCommentDensityKeepsTheExemptionListARatchet(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "ok.go", densityFixture(4, 36))
	write(t, dir, "loud.go", densityFixture(35, 6))
	rep, err := Scan(dir)
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}

	good := []Exemption{{Path: "loud.go", Reason: "the invariant it records cannot be said shorter"}}
	if problems := ValidateExemptions(rep, good); len(problems) != 0 {
		t.Fatalf("a live exemption was rejected: %v", problems)
	}
	var out bytes.Buffer
	if err := Run(dir, &out, good); err != nil {
		t.Fatalf("an exempt file failed the run: %v", err)
	}
	if !strings.Contains(out.String(), "exempt: loud.go") {
		t.Errorf("the exempt file is not reported with its reason:\n%s", out.String())
	}

	tooMany := make([]Exemption, 0, MaxExemptions+1)
	for i := 0; i <= MaxExemptions; i++ {
		tooMany = append(tooMany, Exemption{Path: "loud.go", Reason: "why"})
	}
	if problems := ValidateExemptions(rep, tooMany); len(problems) == 0 ||
		!strings.Contains(problems[0], fmt.Sprintf("%d entries", MaxExemptions+1)) {
		t.Errorf("a list over the cap of %d was accepted: %v", MaxExemptions, problems)
	}

	gone := []Exemption{{Path: "deleted.go", Reason: "why"}}
	if problems := ValidateExemptions(rep, gone); len(problems) != 1 ||
		!strings.Contains(problems[0], "deleted.go") || !strings.Contains(problems[0], "does not exist") {
		t.Errorf("an exemption outliving its file was accepted: %v", problems)
	}

	under := []Exemption{{Path: "ok.go", Reason: "why"}}
	if problems := ValidateExemptions(rep, under); len(problems) != 1 ||
		!strings.Contains(problems[0], "ok.go") || !strings.Contains(problems[0], "ceiling") {
		t.Errorf("an exemption outliving the reason it was granted for was accepted: %v", problems)
	}
	if err := Run(dir, &bytes.Buffer{}, under); err == nil {
		t.Error("a stale exemption did not fail the run")
	}
}

func TestCommentDensityThresholdsStayInsideTheirBounds(t *testing.T) {
	if CeilingPct > 50 {
		t.Errorf("CeilingPct is %d, above the 50%% cap - a prose-heavy tree may not ratchet itself loose", CeilingPct)
	}
	if CeilingPct < 30 {
		t.Errorf("CeilingPct is %d, below the 30%% floor - the next legitimate doc comment would red the gate", CeilingPct)
	}
	if WarnPct != CeilingPct-10 {
		t.Errorf("WarnPct is %d and CeilingPct is %d: the warn band must be exactly 10 points below the ceiling",
			WarnPct, CeilingPct)
	}
}

func TestCommentDensityP90IsTheNearestRankAbove(t *testing.T) {
	var rep Report
	for i := 10; i >= 1; i-- {
		rep.Files = append(rep.Files, File{Path: fmt.Sprintf("f%d.go", i), Counts: Counts{Prose: i, Code: 100 - i}})
	}
	if got, want := rep.P90(), 0.09; got != want {
		t.Errorf("P90 = %v, want %v - rank ceil(0.90 * 10) = 9 of the ascending ratios", got, want)
	}
	if top, ok := rep.Max(); !ok || top.Path != "f10.go" {
		t.Errorf("Max = %v, want f10.go", top)
	}
}

func TestCommentDensityHoldsAcrossTheRepository(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	root, err := RepoRoot(wd)
	if err != nil {
		t.Fatalf("RepoRoot: %v", err)
	}
	var out bytes.Buffer
	if err := Run(root, &out, Exemptions); err != nil {
		t.Fatalf("the repository is over its own ceiling:\n%v", err)
	}
}

// densityFixture builds a Go file with exactly the requested prose and code lines.
func densityFixture(prose, code int) string {
	var b strings.Builder
	b.WriteString("package p\n")
	for i := 0; i < prose; i++ {
		b.WriteString("// a line of prose\n")
	}
	for i := 1; i < code; i++ {
		fmt.Fprintf(&b, "var v%d = %d\n", i, i)
	}
	return b.String()
}

func write(t *testing.T, dir, name, body string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
