package dynhdr

import (
	"bytes"
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// THE REAL-ENCODE FIXTURES. Every source is synthetic (brief §4, T41): a lavfi test pattern,
// 320x240, 24 frames, encoded 10-bit PQ by libx265 with a mastering display, and - for Dolby
// Vision - an RPU generated by `dovi_tool generate` and injected with `dovi_tool inject-rpu`,
// then encoded once more with `-dolbyvision 1` into Matroska so the file carries a DOVI
// configuration record (the recipe of proposal-crop-dv.md, "Test plan"). HDR10+ is written by
// x265 from a one-scene JSON. No step is skipped when a binary is missing: a grader that skips
// is a false green, and these binaries are pinned into the image and CI.

// fixtureMasterDisplay and fixtureCLL are the sources' HDR10 static metadata.
const (
	fixtureMasterDisplay = "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)"
	fixtureCLL           = "1000,400"
	fixtureFrames        = 24
)

// fixtureHDR10Plus is a minimal HDR10+ JSON in hdr10plus_tool's own shape: one scene of
// fixtureFrames frames, which x265 applies to every frame.
const fixtureHDR10Plus = `{"JSONInfo":{"HDR10plusProfile":"B","Version":"1.0"},"SceneInfo":[{"BezierCurveData":` +
	`{"Anchors":[256,512,768,1023,1023,1023,1023,1023,1023],"KneePointX":0,"KneePointY":0},"LuminanceParameters":` +
	`{"AverageRGB":1000,"LuminanceDistributions":{"DistributionIndex":[1,5,10,25,50,75,90,95,99],` +
	`"DistributionValues":[0,100,200,300,400,500,600,700,800]},"MaxScl":[4000,4000,4000]},"NumberOfWindows":1,` +
	`"TargetedSystemDisplayMaximumLuminance":400,"SceneFrameIndex":0,"SceneId":0,"SequenceFrameIndex":0}],` +
	`"SceneInfoSummary":{"SceneFirstFrameIndex":[0],"SceneFrameNumbers":[24]},"ToolInfo":{"Tool":"test","Version":"0"}}`

// realTools are the pinned binaries, from the environment as holdfast names them; a missing
// one fails the test.
func realTools(t *testing.T) Tools {
	t.Helper()
	or := func(k, d string) string {
		if v := os.Getenv(k); v != "" {
			return v
		}
		return d
	}
	tl := ToolsFromEnv(os.Getenv, or("HOLDFAST_FFMPEG", "ffmpeg"), or("HOLDFAST_FFPROBE", "ffprobe"))
	for _, bin := range []string{tl.FFmpeg, tl.FFprobe, tl.DoviTool, tl.HDR10Plus} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Fatalf("%s is required for this fixture and was not found: %v", bin, err)
		}
	}
	return tl
}

func mustRun(t *testing.T, name string, args ...string) {
	t.Helper()
	var out bytes.Buffer
	cmd := exec.Command(name, args...)
	cmd.Stdout, cmd.Stderr = &out, &out
	if err := cmd.Run(); err != nil {
		t.Fatalf("%s %s: %v\n%s", name, strings.Join(args, " "), err, out.String())
	}
}

// x265Colour is the PQ colour description and static metadata every fixture is written with,
// at the x265 parallelism the suite allows (pools=2).
func x265Colour(transfer string) string {
	return "log-level=error:pools=2:colorprim=bt2020:transfer=" + transfer + ":colormatrix=bt2020nc:master-display=" +
		fixtureMasterDisplay + ":max-cll=" + fixtureCLL + ":hdr10-opt=1:repeat-headers=1"
}

// dvSource writes a Dolby Vision Matroska source: profile 8.1 (generate's "8.1"), or 8.4
// with an HLG transfer, with HDR10+ beside the RPU where plus is set.
func dvSource(t *testing.T, tl Tools, dir, name, profile string, plus bool) string {
	t.Helper()
	transfer := "smpte2084"
	if profile == "8.4" {
		transfer = "arib-std-b67"
	}
	params := x265Colour(transfer)
	if plus {
		params += ":dhdr10-info=" + writeFile(t, dir, name+".h10p.json", fixtureHDR10Plus)
	}
	base := filepath.Join(dir, name+".base.hevc")
	mustRun(t, tl.FFmpeg, "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
		"-i", "testsrc2=s=320x240:r=24:d=1", "-pix_fmt", "yuv420p10le", "-c:v", "libx265", "-threads", "2",
		"-x265-params", params, base)
	gen := writeFile(t, dir, name+".gen.json", `{"cm_version":"V40","profile":"`+profile+`","length":24,`+
		`"level6":{"max_display_mastering_luminance":1000,"min_display_mastering_luminance":1,`+
		`"max_content_light_level":1000,"max_frame_average_light_level":400}}`)
	rpu := filepath.Join(dir, name+".rpu.bin")
	mustRun(t, tl.DoviTool, "generate", "-j", gen, "-o", rpu)
	inj := filepath.Join(dir, name+".inj.hevc")
	mustRun(t, tl.DoviTool, "inject-rpu", "-i", base, "--rpu-in", rpu, "-o", inj)
	out := filepath.Join(dir, name+".mkv")
	mustRun(t, tl.FFmpeg, "-hide_banner", "-loglevel", "error", "-y", "-f", "hevc", "-framerate", "24", "-i", inj,
		"-f", "lavfi", "-i", "sine=d=1", "-map", "0:v", "-map", "1:a", "-c:a", "flac",
		"-c:v", "libx265", "-dolbyvision", "1", "-threads", "2", "-pix_fmt", "yuv420p10le", "-crf", "12",
		"-x265-params", params+":vbv-maxrate=20000:vbv-bufsize=20000", out)
	return out
}

// hdr10PlusSource writes an HDR10+ Matroska source with no Dolby Vision.
func hdr10PlusSource(t *testing.T, tl Tools, dir string) string {
	t.Helper()
	out := filepath.Join(dir, "hdr10plus.mkv")
	mustRun(t, tl.FFmpeg, "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
		"-i", "testsrc2=s=320x240:r=24:d=1", "-f", "lavfi", "-i", "sine=d=1", "-c:a", "flac",
		"-pix_fmt", "yuv420p10le", "-c:v", "libx265", "-threads", "2", "-crf", "12",
		"-x265-params", x265Colour("smpte2084")+":dhdr10-info="+writeFile(t, dir, "src.h10p.json", fixtureHDR10Plus), out)
	return out
}

// asProfile7 rewrites the source's DOVI configuration record in place to profile 7 with an
// enhancement layer and compatibility id 6, what a Blu-ray profile 7 stream's record says:
// dovi_tool 2.3.4's generator makes profile 5, 8.1 and 8.4 RPUs and never 7
// (proposal-crop-dv.md, "Profile 7 limit"), so the profile 7 path is driven by a source that
// PROBES as profile 7 and whose RPUs are 8.1, which mode 2 rewrites as 8.1. The record is the
// 24-byte dvcC/dvvC payload: version 1.0, then 7 bits of profile, 6 of level and the
// rpu/el/bl flags, then 4 bits of compatibility id.
func asProfile7(t *testing.T, path string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	p81 := []byte{1, 0, 8<<1 | 0, 1<<3 | 1<<2 | 0<<1 | 1, 1 << 4}
	if bytes.Count(data, p81) != 1 {
		t.Fatalf("the source carries %d profile 8.1 records, want 1", bytes.Count(data, p81))
	}
	i := bytes.Index(data, p81)
	copy(data[i:], []byte{1, 0, 7<<1 | 0, 1<<3 | 1<<2 | 1<<1 | 1, 6 << 4})
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeFile(t *testing.T, dir, name, body string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

// encodeCarrying encodes src the way the engine's command line does for a carried plan:
// libx265 at the source's colour, with the carriage's parameters, codec options and - for a
// conversion - its second input in the video's place. drop names a part left out, to make
// the output each gate must refuse.
func encodeCarrying(t *testing.T, tl Tools, src, out string, p *Prepared, drop string) {
	t.Helper()
	args := []string{"-hide_banner", "-nostdin", "-loglevel", "error", "-y", "-i", src}
	if in := p.InputArgs(); in != nil {
		args = append(append(args, in...), "-map", "1:v:0", "-map", "0:a")
	} else {
		args = append(args, "-map", "0")
	}
	params := x265Colour("smpte2084")
	if drop != "params" {
		params += p.X265Params()
	} else if p.Intent.DolbyVision {
		params += ":vbv-maxrate=1500:vbv-bufsize=1500"
	}
	args = append(args, "-c", "copy", "-c:v", "libx265", "-threads", "2", "-pix_fmt", "yuv420p10le",
		"-preset", "ultrafast", "-crf", "30", "-x265-params", params)
	if drop != "dolbyvision" {
		args = append(args, p.CodecArgs()...)
	}
	mustRun(t, tl.FFmpeg, append(args, "-f", "matroska", out)...)
}

// gate runs the dynamic-HDR gate on out exactly as the engine does: the per-frame counts and
// the stream-level record.
func gate(t *testing.T, tl Tools, out string, want Expectation) error {
	t.Helper()
	c, err := Count(context.Background(), tl.FFprobe, out)
	if err != nil {
		t.Fatalf("counting %s: %v", out, err)
	}
	flat, err := run(exec.Command(tl.FFprobe, "-v", "error", "-select_streams", "v:0",
		"-show_entries", "stream_side_data_list", "-of", "flat=s=.", "--", out))
	if err != nil {
		t.Fatal(err)
	}
	return Check(want, RecordFrom(string(flat)), c)
}

func requireGate(t *testing.T, err error, gate string) {
	t.Helper()
	var ge *GateError
	if !errors.As(err, &ge) || ge.Gate != gate {
		t.Fatalf("the gate returned %v, want a rejection by %s", err, gate)
	}
}

func prepare(t *testing.T, tl Tools, dir, src string, in Intent) *Prepared {
	t.Helper()
	p, err := Prepare(context.Background(), Request{Tools: tl, Intent: in, Source: src,
		JSONPath: filepath.Join(dir, "work: a=b.dynhdr0.json"), RawPath: filepath.Join(dir, "work.dynhdr1"),
		HeadPath: filepath.Join(dir, "work.dynhdr2")})
	if err != nil {
		t.Fatalf("Prepare: %v", err)
	}
	return p
}

// PROFILE 8.1 CARRIED: the real pre-pass derives level 2's ceiling for a 320x240 24 Hz
// source, the encode codes an RPU on every frame under -dolbyvision 1, and the gate passes;
// the same encode without -dolbyvision 1 has no record, and the gate refuses it.
func TestRealFixture_Profile81IsCarriedAndItsRecordGateRedsWithoutIt(t *testing.T) {
	tl := realTools(t)
	dir := t.TempDir()
	src := dvSource(t, tl, dir, "p81", "8.1", false)
	before := md5Of(t, src)
	p := prepare(t, tl, dir, src, Intent{DolbyVision: true, SourceProfile: 8})
	if p.VBV != (VBV{MaxrateKbps: 1500, BufsizeKbit: 1500, Level: "2"}) || p.Frames != fixtureFrames {
		t.Fatalf("the pre-pass established %+v", p)
	}
	out := filepath.Join(dir, "out.mkv")
	encodeCarrying(t, tl, src, out, p, "")
	if err := gate(t, tl, out, p.Expect()); err != nil {
		t.Fatalf("a faithful profile 8.1 output was refused: %v", err)
	}
	dropped := filepath.Join(dir, "dropped.mkv")
	encodeCarrying(t, tl, src, dropped, p, "dolbyvision")
	requireGate(t, gate(t, tl, dropped, p.Expect()), GateDoviRecord)
	if md5Of(t, src) != before {
		t.Fatal("the source changed")
	}
}

// THE RPU-COUNT GATE: an output whose record says profile 8.1 and whose second half carries no
// RPU (the source, then the same stream with its RPUs stripped by the dovi_rpu bitstream
// filter, concatenated by stream copy) is refused by the RPU gate, not passed on its record.
func TestRealFixture_AnOutputMissingRPUsIsRefusedByTheRPUGate(t *testing.T) {
	tl := realTools(t)
	dir := t.TempDir()
	src := dvSource(t, tl, dir, "p81", "8.1", false)
	stripped := filepath.Join(dir, "stripped.mkv")
	mustRun(t, tl.FFmpeg, "-hide_banner", "-loglevel", "error", "-y", "-i", src, "-c", "copy",
		"-bsf:v", "dovi_rpu=strip=1", stripped)
	list := writeFile(t, dir, "list.txt", "file '"+src+"'\nfile '"+stripped+"'\n")
	mixed := filepath.Join(dir, "mixed.mkv")
	mustRun(t, tl.FFmpeg, "-hide_banner", "-loglevel", "error", "-y", "-f", "concat", "-safe", "0", "-i", list,
		"-c", "copy", mixed)
	c, err := Count(context.Background(), tl.FFprobe, mixed)
	if err != nil || c.Frames != 2*fixtureFrames || c.DoviRPU != fixtureFrames {
		t.Fatalf("the fixture counts %+v (%v), want %d frames and %d RPUs", c, err, 2*fixtureFrames, fixtureFrames)
	}
	requireGate(t, gate(t, tl, mixed, Expectation{DolbyVision: true, Profile: 8, CompatID: 1}), GateDoviRPU)
}

// THE PROFILE GATE: an output whose record names another compatibility id than the plan's
// (a profile 8.4 HLG encode, compatibility id 4) is refused by the record gate.
func TestRealFixture_AnOutputOfAnotherCompatibilityIDIsRefusedByTheRecordGate(t *testing.T) {
	tl := realTools(t)
	dir := t.TempDir()
	hlg := dvSource(t, tl, dir, "p84", "8.4", false)
	flat, err := run(exec.Command(tl.FFprobe, "-v", "error", "-show_entries", "stream_side_data_list", "-of", "flat=s=.", hlg))
	if err != nil {
		t.Fatal(err)
	}
	if r := RecordFrom(string(flat)); !r.Readable || r.Profile != 8 || r.CompatID != 4 {
		t.Fatalf("the fixture's record is %+v, want profile 8 compatibility id 4", r)
	}
	err = gate(t, tl, hlg, Expectation{DolbyVision: true, Profile: 8, CompatID: 1})
	requireGate(t, err, GateDoviRecord)
	if !strings.Contains(err.Error(), "compatibility id 4") {
		t.Errorf("the refusal does not name what the output carries: %v", err)
	}
}

// HDR10+ CARRIED: the real extraction validates 24 entries for 24 frames, the encode writes
// them from a path with a colon, a space and an equals sign in it (escaped for -x265-params),
// and the gate passes; the same encode without dhdr10-info carries none, and the HDR10+ gate
// refuses it.
func TestRealFixture_HDR10PlusIsCarriedAndItsGateRedsWithoutIt(t *testing.T) {
	tl := realTools(t)
	dir := t.TempDir()
	src := hdr10PlusSource(t, tl, dir)
	before := md5Of(t, src)
	p := prepare(t, tl, dir, src, Intent{HDR10Plus: true})
	if p.Frames != fixtureFrames || !strings.Contains(p.HDR10PlusJSON, "work: a=b") {
		t.Fatalf("the pre-pass established %+v", p)
	}
	out := filepath.Join(dir, "out.mkv")
	encodeCarrying(t, tl, src, out, p, "")
	if err := gate(t, tl, out, p.Expect()); err != nil {
		t.Fatalf("a faithful HDR10+ output was refused: %v", err)
	}
	dropped := filepath.Join(dir, "dropped.mkv")
	encodeCarrying(t, tl, src, dropped, p, "params")
	requireGate(t, gate(t, tl, dropped, p.Expect()), GateHDR10Plus)
	if md5Of(t, src) != before {
		t.Fatal("the source changed")
	}
}

// BOTH: a source carrying Dolby Vision profile 8.1 AND HDR10+ is carried with both, and both
// gates pass on the one output (docs/design/dynamic-hdr.md#both).
func TestRealFixture_DolbyVisionAndHDR10PlusTogetherAreBothCarried(t *testing.T) {
	tl := realTools(t)
	dir := t.TempDir()
	src := dvSource(t, tl, dir, "both", "8.1", true)
	p := prepare(t, tl, dir, src, Intent{DolbyVision: true, SourceProfile: 8, HDR10Plus: true})
	out := filepath.Join(dir, "out.mkv")
	encodeCarrying(t, tl, src, out, p, "")
	if err := gate(t, tl, out, p.Expect()); err != nil {
		t.Fatalf("an output carrying both was refused: %v", err)
	}
	c, _ := Count(context.Background(), tl.FFprobe, out)
	if c != (Counts{Frames: fixtureFrames, DoviRPU: fixtureFrames, HDR10Plus: fixtureFrames}) {
		t.Errorf("counts %+v", c)
	}
}

// PROFILE 7 CONVERTED: a source probing as profile 7 is converted by the real dovi_tool (mode
// 2, enhancement layer discarded) into a raw stream, which the encode reads at the source's
// exact rate in the video's place, with the audio mapped from the original; the output is
// profile 8.1 with an RPU on every frame, and as long as the source.
func TestRealFixture_Profile7IsConvertedTo81(t *testing.T) {
	tl := realTools(t)
	dir := t.TempDir()
	src := dvSource(t, tl, dir, "p7", "8.1", false)
	asProfile7(t, src)
	p := prepare(t, tl, dir, src, Intent{DolbyVision: true, SourceProfile: 7, Convert: true})
	if p.RawVideo == "" || p.FrameRate != (Rate{24, 1}) {
		t.Fatalf("the conversion established %+v", p)
	}
	if st, err := os.Stat(p.RawVideo); err != nil || st.Size() == 0 {
		t.Fatalf("the converted stream: %v", err)
	}
	out := filepath.Join(dir, "out.mkv")
	encodeCarrying(t, tl, src, out, p, "")
	if err := gate(t, tl, out, p.Expect()); err != nil {
		t.Fatalf("the converted output was refused: %v", err)
	}
	streams, err := run(exec.Command(tl.FFprobe, "-v", "error", "-show_entries", "stream=codec_type", "-of", "csv=p=0", out))
	if err != nil || !strings.HasPrefix(string(streams), "video") || !strings.Contains(string(streams), "audio") {
		t.Errorf("the output's streams are %q (%v), want the converted video then the source's audio", streams, err)
	}
}

func md5Of(t *testing.T, p string) string {
	t.Helper()
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	return string(bytesSum(data))
}

// bytesSum is a cheap content fingerprint: the file itself (the fixtures are a few hundred
// KiB), so "unchanged" is byte equality.
func bytesSum(b []byte) []byte { return append([]byte(nil), b...) }
