package server

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"github.com/NSchatz/holdfast/internal/config"
	"github.com/NSchatz/holdfast/internal/health"
	"github.com/NSchatz/holdfast/internal/node"
	"github.com/NSchatz/holdfast/internal/secret"
	"github.com/NSchatz/holdfast/internal/sourceoffer"
	"github.com/NSchatz/holdfast/internal/store"
	"github.com/NSchatz/holdfast/internal/ui"
)

// Server is the HTTP surface: chi router + read endpoints + SSE + token-gated
// controls. Four independent credentials gate it: the control token
// (`server_auth_token`) on the mutating endpoints, the read token
// (`server_read_token`) on the reads under /api when it is configured, the webhook
// token (`webhook_token`) on the Sonarr and Radarr intake and nowhere else, and the node
// token (`node_token`) on the worker-node lease endpoints and nowhere else. The plain-text
// root page and /metrics are gated by neither, for the reasons given at their routes.
// holdfast ships no frontend, so /api IS the interface. It holds no
// media handles - every mutating action routes through the Controller (scan/pause), which
// cannot touch a file.
type Server struct {
	baseCtx context.Context
	cfg     config.Config
	// token is the RESOLVED control token (secrets K1). It is held here and not read
	// from cfg, because cfg carries the REFERENCE and never the credential: a Config is
	// printed by `validate`, logged at startup and copied by value all over this
	// package, and a plaintext token inside it would ride along on every one of those.
	token secret.Value
	// readToken is the RESOLVED read token (`server_read_token`), held here for exactly
	// the reason the control token is: cfg carries the REFERENCE and never the credential.
	// Empty leaves the read endpoints OPEN, which is every existing install's behaviour.
	readToken secret.Value
	// webhookToken is the RESOLVED webhook credential (`webhook_token`), set with
	// SetWebhookToken. Empty leaves the intake endpoints answering 403.
	webhookToken secret.Value
	// nodeToken is the RESOLVED node credential (`node_token`), set with SetNodeToken.
	// Empty leaves the lease endpoints answering 403.
	nodeToken secret.Value
	// nodes is the lease protocol's server side, set with SetNodes. nil leaves the lease
	// endpoints answering 503 behind their credential: no work is leased.
	nodes   *node.Hub
	store   store.Store
	ctrl    *Controller
	hub     *Hub
	metrics http.Handler
	log     *slog.Logger
	// mux is the chi router itself and not an http.Handler, because the surface document
	// served at /api/schema is generated by WALKING it (S0128). A handler would hide the
	// routes behind ServeHTTP and the document would have to be hand-maintained beside
	// them, which is the one thing http-surface H4 forbids.
	mux *chi.Mux

	// subs is the targeted-scan queue POST /api/scan feeds (S0093). Set once with
	// SetSubmissions, before serving, the way the Controller's own hooks are; with none
	// wired the endpoint refuses rather than accepting work nothing will process.
	subs Submissions

	// health is the library health sweep's live state, read by GET /api/health beside the
	// ledger. nil is a daemon that runs no sweep; the route answers either way.
	health HealthSource

	// ui is the embedded web UI, set with SetUI. nil is a binary that carries none, or a
	// test that wired none: the root path then answers every request with the plain-text
	// page and the asset route answers 404.
	ui *ui.Site
}

// HealthSource is the health sweep's in-memory state, which the ledger does not hold.
type HealthSource interface {
	Live() health.Live
}

// SetHealth wires the health sweep's live state. Set it once, before serving.
func (s *Server) SetHealth(h HealthSource) { s.health = h }

// SetUI wires the embedded web UI (internal/ui). Set it once, before serving. The routes
// exist either way, for the reason SetSubmissions gives.
func (s *Server) SetUI(site *ui.Site) { s.ui = site }

// SetSubmissions wires the targeted-scan queue. Set it once, before serving. The route
// exists either way - a surface that appeared and disappeared with a wiring detail would
// be one no test could enumerate - and answers 503 until this is called.
func (s *Server) SetSubmissions(subs Submissions) { s.subs = subs }

// Wait joins the background work this server started: the scan goroutine and any
// in-flight targeted submission. Call it during shutdown, after the base ctx is cancelled
// and BEFORE the store handle is closed, so neither can issue a store call against a
// closed handle. Submissions still waiting in the queue are dropped unprocessed and
// unrecorded - nothing looked at them, so there is no decision to record.
func (s *Server) Wait() {
	s.ctrl.Wait()
	if s.subs != nil {
		s.subs.Wait()
	}
}

// New builds the Server and its router. baseCtx bounds long-lived handlers (the SSE
// stream watches it, so a shutdown that cancels baseCtx releases open streams
// promptly instead of hanging graceful shutdown). metrics is the Prometheus /metrics
// handler (TRANSCODE-8); pass nil to omit the route. The caller starts hub.Run and
// listens on cfg.EffectiveServerAddr() with s as the handler.
//
// The root path serves the web UI's page to a request that asks for HTML, once SetUI has
// wired one, and RootHandler's plain-text page to every other request; the HTTP JSON API
// under /api is the whole of the machine-readable interface.
//
// token is the control token RESOLVED from cfg's `server_auth_token` reference; an empty
// one leaves the mutating endpoints disabled, exactly as an unconfigured key does.
// readToken is the read token RESOLVED from cfg's `server_read_token` reference; an empty
// one leaves the read endpoints OPEN, which is what every install before this key did.
func New(baseCtx context.Context, cfg config.Config, token, readToken secret.Value, st store.Store, ctrl *Controller, hub *Hub, metrics http.Handler, log *slog.Logger) *Server {
	if log == nil {
		log = slog.Default()
	}
	if baseCtx == nil {
		baseCtx = context.Background()
	}
	s := &Server{baseCtx: baseCtx, cfg: cfg, token: token, readToken: readToken, store: st, ctrl: ctrl, hub: hub, metrics: metrics, log: log}
	s.mux = s.routes()
	return s
}

// ServeHTTP makes Server an http.Handler.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) { s.mux.ServeHTTP(w, r) }

// reads is the handle every READ endpoint answers from, and it is deliberately the HUB's
// rather than a second field of this struct.
//
// At `serve` the hub is built on a read-only door onto the ledger - a handle the database
// itself refuses every write on - so a reporting read cannot occupy the single connection
// the engine's Claim/Advance/Finish writes queue on. Taking it from the hub is what makes
// the stream and the polled endpoints structurally incapable of disagreeing about which
// door they read through: there is one place the reporting handle is supplied, and it is
// the hub's constructor.
//
// s.store stays the WRITE handle, and the mutating endpoints keep using it: the withheld
// paths are recorded through it, and a ledger search is a control-gated read that may as
// well share the writer's connection because it is not on any frame's path.
func (s *Server) reads() store.Store { return s.hub.store }

func (s *Server) routes() *chi.Mux {
	r := chi.NewRouter()
	r.Use(middleware.Recoverer) // a panicking handler must never crash the daemon

	r.Route("/api", func(r chi.Router) {
		// The surface document (http-surface H4), and DELIBERATELY OUTSIDE both token
		// groups below. It carries endpoint paths, methods, status codes, media types,
		// field names and field types - no credential, no configured filesystem path and
		// no per-file datum - so there is nothing behind it for a credential to protect,
		// and a caller has to be able to read the surface before it can authenticate
		// against it. It sits under /api so the root's handler never sees the path and a
		// method this route does not serve is answered 405 by the router.
		r.Get(SchemaPath[len("/api"):], s.handleSchema)

		// Read endpoints - gated on `server_read_token` while it is set, and OPEN while
		// it is not (protected then by the localhost-default bind, and by nothing else).
		//
		// The gate is on THIS group and never on the /api route itself, because the
		// mutating group's own refusals must not change shape: with control disabled it
		// answers 403 naming server_auth_token, and a read gate in front of the whole
		// route would turn that into a 401 about a different key for an operator who has
		// not configured either.
		r.Group(func(r chi.Router) {
			r.Use(s.requireReadToken)
			r.Get("/summary", s.handleSummary)
			r.Get("/queue", s.handleQueue)
			r.Get("/history", s.handleHistory)
			r.Get("/events", s.handleEvents)
			// The library health sweep's report (docs/design/health-sweep.md). A read,
			// and only a read: there is no route that acts on what a sweep found.
			r.Get("/health", s.handleHealth)
		})

		// Mutating endpoints — token required (and disabled entirely when no token
		// is configured). These only ever start a scan, toggle pause, or WITHHOLD a
		// path from the pipeline; none can touch a file.
		//
		// The ledger SEARCH is in here too, and not out of symmetry: the capped read
		// endpoints ship at most a few hundred rows, so a ledger-wide search returns
		// per-file rows they have never served. Gating it makes this a control-gated
		// READ and adds no unauthenticated one.
		r.Group(func(r chi.Router) {
			r.Use(s.requireToken)
			r.Post("/rescan", s.handleRescan)
			// POST /api/scan targets a scan at named files (S0093). It re-opens no row,
			// restores no original and resolves no parked incident: those stay LOCAL
			// commands by ratified operator decision.
			r.Post("/scan", s.handleScan)
			r.Post("/pause", s.handlePause)
			r.Post("/resume", s.handleResume)
			r.Get("/search", s.handleLedgerSearch)
			r.Route("/exclusions", func(r chi.Router) {
				r.Get("/", s.handleExclusionsList)
				r.Post("/", s.handleExcludeAdd)
				r.Delete("/", s.handleExcludeRemove)
			})
		})

		// The Sonarr and Radarr webhook intake (webhook.go), in a group of its OWN: it is
		// gated on `webhook_token` alone, so the credential an arr holds opens these routes
		// and no other, and neither server token opens them. POST and PUT, because an arr's
		// Webhook connection sends one or the other. An accepted file goes through admit,
		// the same admission step POST /api/scan uses.
		r.Group(func(r chi.Router) {
			r.Use(s.requireWebhookToken)
			for _, app := range webhookApps {
				r.Post(WebhookPathPrefix[len("/api"):]+app.name, s.handleWebhook(app))
				r.Put(WebhookPathPrefix[len("/api"):]+app.name, s.handleWebhook(app))
			}
		})

		// The worker-node lease endpoints (internal/node, docs/design/nodes.md), in a group
		// of their OWN: gated on `node_token` alone, so the credential a worker holds can
		// lease a job and upload its output and do nothing else, and no other token opens
		// them. None of them restores, requeues, resolves or re-opens anything: an upload
		// is only ever a candidate for the engine's own gates.
		r.Route(NodePathPrefix[len("/api"):], func(r chi.Router) {
			r.Use(s.requireNodeToken)
			node.Mount(r, func() *node.Hub { return s.nodes })
		})
	})

	// Prometheus metrics (TRANSCODE-8), when enabled. DELIBERATELY NOT GATED, by
	// server_read_token or by anything else: its reachability is governed by
	// metrics_enable alone. The exposition carries counters, a byte total and two
	// histograms labelled only by outcome and by state, so it names no file - and a
	// scrape credential is the one thing a Prometheus deployment most often cannot
	// supply, so gating this would break every existing scrape on upgrade to buy nothing.
	// The premise is asserted in internal/metrics: no library path reaches the exposition.
	if s.metrics != nil {
		r.Handle("/metrics", s.metrics)
	}

	// The root path, and DELIBERATELY NOT GATED either: it is the web UI's page, or a
	// plain-text page naming the API's endpoints, and both carry the AGPL section 13
	// source offer and no library datum, so there is nothing behind it for a credential
	// to protect. The same holds for the UI's static assets, which are the page's script
	// and stylesheet and name no file of any library.
	plain := RootHandler()
	r.Get("/", s.handleRoot(plain))
	r.Get(UIAssetsPrefix+"*", s.handleUIAsset)
	return r
}

// UIAssetsPrefix is the path the web UI's static assets are served under: the one
// directory of the build the page references (internal/ui.AssetsDir).
const UIAssetsPrefix = "/" + ui.AssetsDir + "/"

// uiContentSecurityPolicy is sent with the page. The build has no inline script and no
// inline style and loads nothing from another origin (web/src/page.test.ts holds the page
// to that, web/vite.config.ts inlines no asset), so every source is this server alone: a
// script injected into the page by any route has nowhere to load from and nothing to
// run as. It names the API as the one thing the page may connect to, forbids framing,
// and gives a form nowhere to post.
const uiContentSecurityPolicy = "default-src 'none'; script-src 'self'; style-src 'self'; " +
	"img-src 'self'; font-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; " +
	"frame-ancestors 'none'"

// handleRoot answers "/" with one of two representations of the same root: the web UI's
// page for a request that asks for HTML, and the plain-text page for every other request.
//
// The plain-text page is the DEFAULT, and that is deliberate. It is what "/" answered
// before there was a UI, so a client that never asked for HTML - curl, a health probe, a
// script that greps the banner - gets the bytes it always got, and the surface document's
// description of this path stays true of a request that states no preference. A browser
// navigation always names text/html, so a person gets the UI. Both carry the source
// offer: the page has it written in by internal/ui.Load, the text page ends with it.
//
// With no UI wired, or on a build that carries none, every request gets the text page.
func (s *Server) handleRoot(plain http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// The answer depends on Accept in either branch, and a cache must know it.
		w.Header().Add("Vary", "Accept")
		if s.ui == nil || !acceptsHTML(r.Header.Values("Accept")) {
			plain(w, r)
			return
		}
		h := w.Header()
		h.Set("Content-Type", "text/html; charset=utf-8")
		h.Set("Content-Security-Policy", uiContentSecurityPolicy)
		h.Set("X-Content-Type-Options", "nosniff")
		h.Set("Referrer-Policy", "no-referrer")
		// The page names its assets by content hash, so it is the one file that must be
		// asked for again: a cached page would pin a browser to a build that is gone.
		h.Set("Cache-Control", "no-cache")
		_, _ = w.Write(s.ui.Page())
	}
}

// handleUIAsset serves one static asset of the web UI. It answers only for a name
// internal/ui.Load read out of the build - a map lookup, never a path resolved against
// anything at request time - and 404 for every other path, including every path when no
// UI is wired.
func (s *Server) handleUIAsset(w http.ResponseWriter, r *http.Request) {
	if s.ui == nil {
		http.NotFound(w, r)
		return
	}
	asset, ok := s.ui.Asset(strings.TrimPrefix(r.URL.Path, UIAssetsPrefix))
	if !ok {
		http.NotFound(w, r)
		return
	}
	h := w.Header()
	h.Set("Content-Type", asset.ContentType)
	h.Set("X-Content-Type-Options", "nosniff")
	// A name carries the hash of its content, so the bytes behind a name never change.
	h.Set("Cache-Control", "public, max-age=31536000, immutable")
	_, _ = w.Write(asset.Body)
}

// acceptsHTML reports whether an Accept header asks for HTML by name: a media range of
// text/html or application/xhtml+xml with a quality above zero. A wildcard is not a
// request for HTML - `*/*` is what curl sends and what a client that states no preference
// means - and neither is an absent or unreadable header. An unreadable quality reads as
// zero: the plain-text page is the answer whenever the request is not clear.
func acceptsHTML(accept []string) bool {
	for _, line := range accept {
		for _, part := range strings.Split(line, ",") {
			fields := strings.Split(part, ";")
			switch strings.ToLower(strings.TrimSpace(fields[0])) {
			case "text/html", "application/xhtml+xml":
			default:
				continue
			}
			q := 1.0
			for _, param := range fields[1:] {
				name, value, ok := strings.Cut(strings.TrimSpace(param), "=")
				if !ok || !strings.EqualFold(strings.TrimSpace(name), "q") {
					continue
				}
				parsed, err := strconv.ParseFloat(strings.TrimSpace(value), 64)
				if err != nil || parsed < 0 || parsed > 1 {
					parsed = 0
				}
				q = parsed
			}
			if q > 0 {
				return true
			}
		}
	}
	return false
}

// RootHandler serves the plain-text page at "/": a line naming the read endpoints, and
// the AGPL section 13 source offer. It is the whole of the root response on a build that
// carries no web UI, and the root's answer to every request that does not ask for HTML on
// one that does (handleRoot). It is a root response a remote user can get, so it owes that
// offer (LICENSE-3) - the source URL in effect, the licence name and the build identity,
// with the literal label immediately before the URL. No markup, so the URL is written
// verbatim.
//
// It resolves the offer through the SAME accept test the daemon runs at startup, and
// refuses if the value was rejected: a rejected value must not reach a root response.
// In the daemon that refusal has already happened before any listener exists - this
// branch is reachable only in process, where there is no listener to refuse and no exit
// code to return.
func RootHandler() http.HandlerFunc {
	const banner = "holdfast API is running. See /api/summary, /api/queue, /api/history, /api/events.\n"
	offer, err := sourceoffer.Resolve()
	if err != nil {
		msg := "holdfast refuses to serve the root path: " + err.Error() + "\n"
		return func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, msg, http.StatusServiceUnavailable)
		}
	}
	body := []byte(banner + "\n" + offer.Text())
	return func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		_, _ = w.Write(body)
	}
}

// --- read endpoints ----------------------------------------------------------

// controlState is the at-a-glance status payload (no per-job rows). It carries BOTH
// the durable lifetime reclaimed total (TRANSCODE-14 — the figure that survives a
// restart) and the per-process session figure, mirroring the SSE snapshot so a client
// polling /api/summary sees the same two numbers the live stream pushes.
//
// It also carries the whole-ledger aggregates (DASH-7) under the same key and the same
// shape the SSE snapshot uses, so the figures are not reachable only over a live stream:
// a client that polls sees exactly what a client that subscribes sees. Like every other
// field here they are aggregates, so this adds no per-file datum to a read surface that
// needs no authorization.
type controlState struct {
	Summary                map[string]int `json:"summary"`
	BytesReclaimedSession  int64          `json:"bytes_reclaimed_session"`
	BytesReclaimedLifetime int64          `json:"bytes_reclaimed_lifetime"`
	Paused                 bool           `json:"paused"`
	Scanning               bool           `json:"scanning"`
	Aggregates             aggregatesDTO  `json:"aggregates"`
}

func (s *Server) handleSummary(w http.ResponseWriter, r *http.Request) {
	sum, err := s.reads().Summary(r.Context())
	if err != nil {
		s.fail(w, "summary", err)
		return
	}
	counts := make(map[string]int, len(sum))
	for st, n := range sum {
		counts[string(st)] = n
	}
	// The same whole-ledger figure set the stream publishes, from the same cache and
	// under the same refresh interval: a client that polls sees what a client that
	// subscribes sees, and polling this endpoint cannot make the figures cost more than
	// one refresh per interval however often it is called.
	writeJSON(w, http.StatusOK, controlState{
		Summary:                counts,
		BytesReclaimedSession:  s.hub.BytesReclaimed(),
		BytesReclaimedLifetime: s.hub.ReclaimedLifetime(),
		Paused:                 s.ctrl.Paused(),
		Scanning:               s.ctrl.Scanning(),
		Aggregates:             aggregatesOf(s.hub.ledgerFigures(r.Context(), true)),
	})
}

// The named wire shapes for the handlers that used to encode an anonymous map literal
// (S0128). They exist so the surface document has a CLOSED set of named fields to
// describe for every JSON endpoint: a map[string]any is an open object, and a document
// declaring one makes every validator pass while describing nothing at all.
//
// THE FIELD ORDER IS THE MAP'S OWN, which is alphabetical, because encoding/json sorts a
// map's keys and writes a struct's fields in declaration order. These types therefore
// encode BYTE-IDENTICAL JSON to the literals they replaced - asserted in schema_test.go -
// so no caller sees a change and the diff gate sees no difference from this task.

// queueResponse is the body of GET /api/queue.
type queueResponse struct {
	Now        int64       `json:"now"`
	Queue      []jobDTO    `json:"queue"`
	QueueTotal rowTotalDTO `json:"queue_total"`
}

// historyResponse is the body of GET /api/history.
type historyResponse struct {
	History      []jobDTO    `json:"history"`
	HistoryTotal rowTotalDTO `json:"history_total"`
}

// rescanResponse is the body of POST /api/rescan, under 202 and under 409 alike.
type rescanResponse struct {
	Paused   bool   `json:"paused"`
	Reason   string `json:"reason"`
	Scanning bool   `json:"scanning"`
	Started  bool   `json:"started"`
}

// controlToggleResponse is the body of POST /api/pause and POST /api/resume.
type controlToggleResponse struct {
	Paused   bool `json:"paused"`
	Scanning bool `json:"scanning"`
}

func (s *Server) handleQueue(w http.ResponseWriter, r *http.Request) {
	jobs, err := s.reads().List(r.Context(), activeAndPending, queueLimit)
	if err != nil {
		s.fail(w, "queue", err)
		return
	}
	// Same projection the SSE snapshot uses, live progress included, and the same "now"
	// basis for an in-state age — a client that polls this endpoint must not see a
	// different picture of a running job than one watching the stream.
	//
	// queue_total is the same field, under the same name and in the same shape, that the
	// SSE snapshot carries: the count of matching rows in the ledger, so a response that
	// shipped at most queueLimit of them says what it capped against instead of leaving a
	// client to derive it.
	writeJSON(w, http.StatusOK, queueResponse{
		Now:        time.Now().Unix(),
		Queue:      s.hub.queueDTOs(jobs),
		QueueTotal: rowTotalOf(s.hub.ledgerFigures(r.Context(), true).QueueTotal, queueLimit),
	})
}

func (s *Server) handleHistory(w http.ResponseWriter, r *http.Request) {
	limit := historyLimit
	if q := r.URL.Query().Get("limit"); q != "" {
		// Clamp a requested limit into (0, historyLimit]; anything larger keeps the
		// cap, anything else keeps the default. `<=` lets a caller ask for exactly
		// the cap.
		if n, err := strconv.Atoi(q); err == nil && n > 0 && n <= limit {
			limit = n
		}
	}
	jobs, err := s.reads().List(r.Context(), terminal, limit)
	if err != nil {
		s.fail(w, "history", err)
		return
	}
	// history_total counts the matching rows in the LEDGER, so it is the same figure
	// whether the caller took the cap or asked for fewer: `cap` moves with the request,
	// `count` does not. A total that tracked the request would just be len(history).
	writeJSON(w, http.StatusOK, historyResponse{
		History:      toDTOs(jobs),
		HistoryTotal: rowTotalOf(s.hub.ledgerFigures(r.Context(), true).HistoryTotal, limit),
	})
}

// handleEvents is the SSE stream: an initial snapshot, then a fresh snapshot on
// every engine transition / control change, plus a periodic heartbeat comment so
// idle connections (and proxies) stay open.
func (s *Server) handleEvents(w http.ResponseWriter, r *http.Request) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no") // disable proxy buffering (nginx)

	// Subscribe builds this client's own first frame and seeds the channel with it, so
	// the initial state a just-connected client renders is read AT THE MOMENT IT
	// SUBSCRIBED. The handler no longer takes a second snapshot of its own: one build
	// per subscription, arriving on the same channel as every frame after it.
	ch, cancel := s.hub.Subscribe(r.Context())
	defer cancel()

	heartbeat := time.NewTicker(25 * time.Second)
	defer heartbeat.Stop()

	for {
		select {
		case <-r.Context().Done():
			return
		case <-s.baseCtx.Done(): // server shutting down — release the stream
			return
		case data := <-ch:
			writeSSE(w, data)
			flusher.Flush()
		case <-heartbeat.C:
			_, _ = fmt.Fprint(w, ": ping\n\n")
			flusher.Flush()
		}
	}
}

// --- mutating endpoints (token-gated) ----------------------------------------

func (s *Server) handleRescan(w http.ResponseWriter, _ *http.Request) {
	started, reason := s.ctrl.Rescan()
	code := http.StatusAccepted
	if !started {
		code = http.StatusConflict // paused / already scanning
	}
	writeJSON(w, code, rescanResponse{
		Paused:   s.ctrl.Paused(),
		Reason:   reason,
		Scanning: s.ctrl.Scanning(),
		Started:  started,
	})
}

func (s *Server) handlePause(w http.ResponseWriter, _ *http.Request) {
	s.ctrl.Pause()
	writeJSON(w, http.StatusOK, controlToggleResponse{Paused: s.ctrl.Paused(), Scanning: s.ctrl.Scanning()})
}

func (s *Server) handleResume(w http.ResponseWriter, _ *http.Request) {
	s.ctrl.Resume()
	writeJSON(w, http.StatusOK, controlToggleResponse{Paused: s.ctrl.Paused(), Scanning: s.ctrl.Scanning()})
}

// --- auth --------------------------------------------------------------------

// requireToken gates mutating endpoints. With no token resolved, control is
// DISABLED (403) - remote control is off until an operator opts in by pointing
// server_auth_token at a secret. A resolved token is compared in constant time, and it
// is never written to a response body, a header or a log: the 401 says "unauthorized"
// and nothing about what would have been accepted.
func (s *Server) requireToken(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if s.token.Empty() {
			http.Error(w, "control disabled: point server_auth_token at a secret "+
				"(file:/run/secrets/... or cmd:...) to enable rescan/pause/resume, the ledger search "+
				"and the withheld paths - see docs/secrets.md",
				http.StatusForbidden)
			return
		}
		got := bearerToken(r.Header.Get("Authorization"))
		if subtle.ConstantTimeCompare([]byte(got), []byte(s.token.Expose())) != 1 {
			w.Header().Set("WWW-Authenticate", `Bearer realm="holdfast"`)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// requireReadToken gates the read endpoints under /api on `server_read_token`. With no
// read token resolved it is a pass-through: the read surface is OPEN, which is the
// shipped default and every existing install's behaviour, and a key that gated on upgrade
// would lock out every client that never sent a credential.
//
// With one resolved, a request must present EITHER the read token OR the control token.
// The control token is accepted here because one Authorization header cannot carry two
// values, so an operator holding the more privileged credential would otherwise be locked
// out of the less privileged surface. The reverse never holds: requireToken compares
// against the control token alone, so a read token buys no mutation.
//
// Both comparisons are constant time and BOTH ARE ALWAYS RUN - the results are combined
// with a bitwise OR rather than `||`, because a short circuit would make the response
// time say which of the two credentials was presented. Neither value reaches a response
// body, a header or a log: the 401 says "unauthorized" and nothing about what would have
// been accepted, and it names no media path, which is the whole reason this gate exists.
//
// It is MIDDLEWARE, so /api/events is refused before handleEvents runs at all: no
// snapshot, no heartbeat and no path is written to an unauthenticated stream.
func (s *Server) requireReadToken(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if s.readToken.Empty() {
			next.ServeHTTP(w, r)
			return
		}
		presented := []byte(bearerToken(r.Header.Get("Authorization")))
		ok := subtle.ConstantTimeCompare(presented, []byte(s.readToken.Expose()))
		// The control token is only a credential when one is configured. Without this
		// guard an EMPTY control token would compare equal to an absent Authorization
		// header, and a daemon with the controls disabled would serve its read API to
		// anyone who sent no credential at all - the exact hole this gate closes.
		if !s.token.Empty() {
			ok |= subtle.ConstantTimeCompare(presented, []byte(s.token.Expose()))
		}
		if ok != 1 {
			w.Header().Set("WWW-Authenticate", `Bearer realm="holdfast"`)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// NodePathPrefix is the path the worker-node lease endpoints sit under. The version is in
// the path: a worker and a server run the same holdfast version, and a later protocol
// would be mounted beside this one.
const NodePathPrefix = "/api/node/v1"

// SetNodeToken hands the server the RESOLVED node credential (`node_token`). Set it once,
// before serving. The lease routes exist either way, so the surface is the same in every
// deployment, and they answer 403 until a non-empty value is set.
func (s *Server) SetNodeToken(token secret.Value) { s.nodeToken = token }

// SetNodes wires the lease protocol's server side. Set it once, before serving. Until it
// is set the lease endpoints answer 503 behind their credential.
func (s *Server) SetNodes(h *node.Hub) { s.nodes = h }

// requireNodeToken gates the lease endpoints on `node_token`, and on nothing else. With no
// node credential resolved the endpoints are DISABLED (403), as every mutating endpoint is
// without its credential: nodes are off until an operator opts in.
//
// The control token, the read token and the webhook token are NOT accepted here, and this
// credential authorises nothing anywhere else - the other gates compare against their own
// tokens only - so a stolen node token can lease a job and upload a candidate and cannot
// pause, exclude, search, scan or queue. The comparison is constant time, and the
// credential never reaches a response body, a header or a log.
func (s *Server) requireNodeToken(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if s.nodeToken.Empty() {
			http.Error(w, "worker nodes disabled: point node_token at a secret "+
				"(file:/run/secrets/... or cmd:...) to enable the lease endpoints under "+
				NodePathPrefix+" - see docs/secrets.md",
				http.StatusForbidden)
			return
		}
		got := bearerToken(r.Header.Get("Authorization"))
		if subtle.ConstantTimeCompare([]byte(got), []byte(s.nodeToken.Expose())) != 1 {
			w.Header().Set("WWW-Authenticate", `Bearer realm="holdfast"`)
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// bearerToken extracts the token from an "Authorization: Bearer <token>" header
// (case-insensitive scheme), or "" if absent/malformed.
func bearerToken(header string) string {
	const prefix = "bearer "
	if len(header) < len(prefix) || !strings.EqualFold(header[:len(prefix)], prefix) {
		return ""
	}
	return strings.TrimSpace(header[len(prefix):])
}

// --- helpers -----------------------------------------------------------------

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}

// writeSSE writes one SSE "snapshot" event. data is compact JSON (no embedded
// newlines), so a single data: line is correct.
func writeSSE(w http.ResponseWriter, data []byte) {
	_, _ = fmt.Fprintf(w, "event: snapshot\ndata: %s\n\n", data)
}

// handleHealth answers GET /api/health from the reporting door: the sweep under way, the
// last one that finished, and the files each found corrupt or unreadable.
func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	live := health.Live{State: health.StateOff}
	if s.health != nil {
		live = s.health.Live()
	}
	rep, err := health.BuildReport(r.Context(), s.reads(), s.cfg.HealthSweepInterval(), live)
	if err != nil {
		s.fail(w, "health", err)
		return
	}
	writeJSON(w, http.StatusOK, rep)
}

func (s *Server) fail(w http.ResponseWriter, what string, err error) {
	s.log.Warn("api read failed", "endpoint", what, "err", err)
	http.Error(w, "internal error reading "+what, http.StatusInternalServerError)
}

// StartScanLoop kicks an initial scan (unless paused) and, when intervalSec > 0,
// re-scans on that interval until ctx is cancelled. It is the serve command's
// driver; overlap and pause are handled by the Controller (a tick that lands while
// a scan runs or while paused is simply refused). Runs in the caller's goroutine —
// serve launches it in the background.
func (s *Server) StartScanLoop(ctx context.Context, intervalSec int) {
	if started, reason := s.ctrl.Rescan(); !started {
		s.log.Info("initial scan not started", "reason", reason)
	}
	if intervalSec <= 0 {
		return
	}
	ticker := time.NewTicker(time.Duration(intervalSec) * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			if started, reason := s.ctrl.Rescan(); !started {
				s.log.Debug("periodic scan skipped", "reason", reason)
			}
		}
	}
}
